import type { CSSProperties } from "react";

export const portalStyles: Record<string, CSSProperties> = {
  page: {
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    background: "#f6f5f3",
    minHeight: "100vh",
    display: "flex",
    justifyContent: "center",
    padding: "48px 16px",
  },
  card: {
    background: "#ffffff",
    borderRadius: 16,
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
    padding: 32,
    maxWidth: 560,
    width: "100%",
  },
  heading: { fontSize: 24, margin: "0 0 8px", color: "#1a1a1a" },
  subheading: { fontSize: 14, color: "#6b6b6b", margin: "0 0 24px" },
  form: { display: "flex", flexDirection: "column", gap: 16 },
  label: { display: "flex", flexDirection: "column", gap: 6, fontSize: 13, color: "#333" },
  input: {
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid #d9d9d9",
    fontSize: 15,
  },
  button: {
    marginTop: 8,
    padding: "12px 16px",
    borderRadius: 8,
    border: "none",
    background: "#1a1a1a",
    color: "#fff",
    fontSize: 15,
    cursor: "pointer",
  },
  secondaryButton: {
    marginTop: 8,
    padding: "12px 16px",
    borderRadius: 8,
    border: "1px solid #d9d9d9",
    background: "#fff",
    color: "#1a1a1a",
    fontSize: 15,
    cursor: "pointer",
  },
  error: {
    marginTop: 20,
    color: "#b3261e",
    fontSize: 14,
  },
  results: { marginTop: 24 },
  resultsHeading: { fontSize: 16, margin: "0 0 12px" },
  itemList: { listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 10 },
  item: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: 14,
    borderBottom: "1px solid #eee",
    paddingBottom: 10,
  },
  optionCard: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "14px 16px",
    borderRadius: 10,
    border: "1px solid #e2e2e2",
    cursor: "pointer",
  },
  optionLabel: { display: "flex", gap: 10, alignItems: "flex-start", fontSize: 15, fontWeight: 600, color: "#1a1a1a" },
  optionMessage: { fontSize: 13, color: "#6b6b6b", marginLeft: 24, lineHeight: 1.5 },
  breadcrumb: { fontSize: 12, color: "#999", margin: "0 0 4px", textTransform: "uppercase", letterSpacing: 0.5 },
};
