# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "802577071443a106b8e17d1c982d2ae3"
name = "Mod Easy Returns"
application_url = "https://mod-easy-returns.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_files,write_files,write_returns,write_orders,write_draft_orders"

[auth]
redirect_urls = [ "https://mod-easy-returns.onrender.com/api/auth" ]

[app_proxy]
url = "https://mod-easy-returns.onrender.com/apps/returns"
subpath = "returns"
prefix = "apps"
